In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\\Users\\Arjun Singh Tomar\\Downloads\\archive (21)\\data.csv')

In [4]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [5]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.dtypes

date              object
price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
street            object
city              object
statezip          object
country           object
dtype: object

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
df['street'].value_counts()

street
2520 Mulberry Walk NE     4
2500 Mulberry Walk NE     3
9413 34th Ave SW          2
6008 8th Ave NE           2
11034 NE 26th Pl          2
                         ..
1404 Broadmoor Dr E       1
3249 E Ames Lake Dr NE    1
6032 35th Ave NE          1
1006 NE Ravenna Blvd      1
18717 SE 258th St         1
Name: count, Length: 4525, dtype: int64

In [13]:
street_freq = df['street'].value_counts()
df['street'] = df['street'].map(street_freq)
df['street'] = df['street'].map(street_freq).fillna(1)

In [14]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,1.0,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,1.0,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,1.0,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,1.0,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,1.0,Redmond,WA 98052,USA

In [15]:
street_freq = df['statezip'].value_counts()

df['statezip'] = df['statezip'].map(street_freq)
df['statezip'] = df['statezip'].map(street_freq).fillna(0)

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
oe = OneHotEncoder(sparse_output = False ,handle_unknown = 'ignore')

In [22]:
df = pd.get_dummies(df, columns=['city'], dtype=int)

In [23]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,city_SeaTac,city_Seattle,city_Shoreline,city_Skykomish,city_Snoqualmie,city_Snoqualmie Pass,city_Tukwila,city_Vashon,city_Woodinville,city_Yarrow Point
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,...,0,0,1,0,0,0,0,0,0,0
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,...,0,1,0,0,0,0,0,0,0,0
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,...,0,0,0,0,0,0,0,0,0,0

In [24]:
df['date'] = pd.to_datetime(df['date'])

In [28]:
df['years'] = df['date'].dt.year
df['months'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['dayofweek'] = df['date'].dt.dayofweek

In [30]:
df.drop(columns = ['date'],axis = 1,inplace=True)

In [31]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,...,city_Snoqualmie,city_Snoqualmie Pass,city_Tukwila,city_Vashon,city_Woodinville,city_Yarrow Point,years,months,day,dayofweek
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,...,0,0,0,0,0,0,2014,5,2,4
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,...,0,0,0,0,0,0,2014,5,2,4
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,...,0,0,0,0,0,0,2014,5,2,4
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,...,0,0,0,0,0,0,2014,5,2,4
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,...,0,0,0,0,0,0,2014,5,2,4

In [48]:
df = df.drop(columns = ['country'],axis = 1)

In [49]:
X = df.drop(columns = ['price'],axis=1)
y = df['price']

In [50]:
from sklearn.model_selection import train_test_split

In [58]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size = 0.33,random_state=42
)

In [59]:
from sklearn.linear_model import Ridge

In [60]:
rd = Ridge()

In [61]:
rd.fit(X_train,y_train)

Ridge()

In [62]:
y_pred = rd.predict(X_test)

In [63]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [64]:
mean_absolute_error(y_test,y_pred)

155766.5771673129

In [65]:
mean_squared_error(y_test,y_pred)

608804512251.447

In [66]:
r2_score(y_test,y_pred)

0.08513186946624385

In [67]:
new_house = X_test.iloc[[0]]

prediction = rd.predict(new_house)

In [68]:
prediction

array([399104.40285543])

In [69]:
from sklearn.linear_model import Lasso

In [70]:
ls = Lasso()

In [71]:
ls.fit(X_train,y_train)

C:\Users\Arjun Singh Tomar\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.088126e+13, tolerance: 4.517e+10
  model = cd_fast.enet_coordinate_descent(

Lasso()

In [72]:
y_pred_ls = ls.predict(X_test)

In [74]:
mean_absolute_error(y_test,y_pred_ls)

155474.52137434608

In [75]:
mean_squared_error(y_test,y_pred_ls)

608727100924.252

In [76]:
r2_score(y_test,y_pred_ls)

0.08524819770423786

In [77]:
new_house_ls = X_test.iloc[[0]]

prediction = rd.predict(new_house_ls)

In [78]:
prediction

array([399104.40285543])