In [46]:
import pandas as pd

In [47]:
import numpy as np
import matplotlib.pyplot as plt

In [48]:
import seaborn as sns

In [49]:
df = pd.read_csv(r'C:\\Users\\Arjun Singh Tomar\\Downloads\\archive (21)\\data.csv')

In [50]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [51]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [52]:
df.duplicated().sum()

np.int64(0)

In [53]:
df.dtypes

date              object
price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
street            object
city              object
statezip          object
country           object
dtype: object

In [54]:
df['street'].nunique()

4525

In [55]:
df.shape

(4600, 18)

In [56]:
street_freq = df['street'].value_counts()

df['street'] = df['street'].map(street_freq)
df['street'] = df['street'].map(street_freq).fillna(0)

In [57]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,0.0,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,0.0,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,0.0,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,0.0,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,0.0,Redmond,WA 98052,USA

In [58]:
df['city'].value_counts()

city
Seattle                1573
Renton                  293
Bellevue                286
Redmond                 235
Issaquah                187
Kirkland                187
Kent                    185
Auburn                  176
Sammamish               175
Federal Way             148
Shoreline               123
Woodinville             115
Maple Valley             96
Mercer Island            86
Burien                   74
Snoqualmie               71
Kenmore                  66
Des Moines               58
North Bend               50
Covington                43
Duvall                   42
Lake Forest Park         36
Bothell                  33
Newcastle                33
SeaTac                   29
Tukwila                  29
Vashon                   29
Enumclaw                 28
Carnation                22
Normandy Park            18
Clyde Hill               11
Medina                   11
Fall City                11
Black Diamond             9
Ravensdale                7
Pacific                   6
Algona                    5
Yarrow Point              4
Skykomish                 3
Preston                   2
Milton                    2
Inglewood-Finn Hill       1
Snoqualmie Pass           1
Beaux Arts Village        1
Name: count, dtype: int64

In [59]:
df['statezip'].value_counts()

statezip
WA 98103    148
WA 98052    135
WA 98117    132
WA 98115    130
WA 98006    110
           ...
WA 98047      6
WA 98288      3
WA 98050      2
WA 98354      2
WA 98068      1
Name: count, Length: 77, dtype: int64

In [60]:
street_freq = df['statezip'].value_counts()

df['statezip'] = df['statezip'].map(street_freq)
df['statezip'] = df['statezip'].map(street_freq).fillna(0)

In [61]:
df['country'].value_counts()

country
USA    4600
Name: count, dtype: int64

In [62]:
df.drop('country', axis=1, inplace=True)

In [63]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

city_encoded = ohe.fit_transform(df[['city']])

city_encoded_df = pd.DataFrame(
    city_encoded,
    columns=ohe.get_feature_names_out(['city']),
    index=df.index
)

df = pd.concat([df.drop('city', axis=1), city_encoded_df], axis=1)

In [64]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,city_SeaTac,city_Seattle,city_Shoreline,city_Skykomish,city_Snoqualmie,city_Snoqualmie Pass,city_Tukwila,city_Vashon,city_Woodinville,city_Yarrow Point
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [66]:
df['date'] = pd.to_datetime(df['date'])

In [68]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['dayofweek'] = df['date'].dt.dayofweek

In [69]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,city_Snoqualmie,city_Snoqualmie Pass,city_Tukwila,city_Vashon,city_Woodinville,city_Yarrow Point,year,month,day,dayofweek
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,5,2,4
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,5,2,4
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,5,2,4
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,5,2,4
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,5,2,4

In [71]:
df.drop('date', axis=1, inplace=True)

In [72]:
from sklearn.model_selection import train_test_split

In [74]:
X = df.drop(columns = ['price'],axis = 1)
y = df['price']

In [75]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size = 0.2,random_state=42
)

In [76]:
from sklearn.linear_model import LinearRegression

In [77]:
lr = LinearRegression()

In [78]:
lr.fit(X_train,y_train)

LinearRegression()

In [79]:
y_pred = lr.predict(X_test)

In [81]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [82]:
mean_absolute_error(y_test,y_pred)

173260.74822759264

In [83]:
mean_squared_error(y_test,y_pred)

977070474909.0686

In [84]:
r2_score(y_test,y_pred)

0.04194344137592221